Added the option to add more than one node (requires new config file)
redfire/tp-link-hs110-munisense-connector pull request #1
Opened 2017-03-25 16:45 UTC by Mattie112

You can now have multiple nodes, please configure them in the config file:

`    local: {
        devices: {
            "warmtewinner": {
                ip: "192.168.101.198",
                eui64: "f105:00ff:0000:0001"
            },
            "plug_2": {
                ip: "192.168.101.197",
                eui64: "f105:00ff:0000:0002"
            }
        }
    },
`

2017-03-26 10:40 UTC, jeroenmaas requested changes
I've got one small comment. Other than that the change looks good. I'll approve the pull request once the comment has been resolved.

2017-03-26 10:40 UTC, redfire commented on config-example.js
> +            "boiler": {
I would've expected devices to be an array. It feel strange to make it an object and having the keys be an arbitrary name.

Please change to something like this:

devices: [
{
ip: "",
eui64: "",
name: ""
},
{
}
]

and name is optional ofcourse.

2017-03-27 17:12 UTC, Mattie112 commented
Allright, updated :)

2017-03-27 17:14 UTC, Mattie112 reviewed
Done!

2017-03-30 20:29 UTC, merged